### ISSUE TITLE
Negative Tiles is incompatible with 3072

### ISSUE THREAD

**Issue by James103** [MathCookie17/The-2048-Power-Compendium#1]
To reproduce: turn on Negative Tiles in page 4 of the Modifiers (it doesn't matter if it's interacting or not), then start a new game of 3072.
The board is completely blank and will result in an immediate game over.

Even if "You have to move on every turn" is turned off, pressing the spacebar key to let new tiles spawn does nothing.

**Comment by MathCookie17** [comment]
Oh hey, another bug from v1.4. that somehow remained uncaught until now! Isn't that just swell? I sure hope there aren't any more of these, but there probably are
